const states = {
    PROMPTED_FOR_DAILY_SPECIALS: 'PROMPTED_FOR_DAILY_SPECIALS',
    PROMPTED_TO_ORDER_DAILY_SPECIAL: 'PROMPTED_TO_ORDER_DAILY_SPECIAL',
    PROMPTED_TO_CUSTOMIZE : 'PROMPTED_TO_CUSTOMIZE',
    PROMPTED_TO_ADD_TO_ORDER: 'PROMPTED_TO_ADD_TO_ORDER',
    PROMPTED_TO_ORDER_SPECIAL : 'PROMPTED_TO_ORDER_SPECIAL',
    PROMPTED_TO_CUSTOMIZE_SPECIAL_MENU : 'PROMPTED_TO_CUSTOMIZE_SPECIAL_MENU'
};

module.exports = states;